a = input("enter the a number:")
a = int(a)
print(a,type(a))
b = input('Enter the a decimal number:')
b = float(b)
print(b,type(b))
c = input("Enter the value of c:")
c = int(c)
d = 6
print(c+d)
a = 56
print("Number is :"+str(a))
a = input("Enter  number:")
b = input("Enter number:")
print("before conversion:",type(a))
sum = int(a) + int(b)
print('sum =',sum)
a = input("Enter the value of a:")
print("Before conversion:",type(a))
a = int(a)
print("After conversion:",type(a))
a = int(input("enter the value of a:"))
b = int(input("Enter the value of b:"))
print("Sum =",a+b)